### ISSUE TITLE
Usability: avoid double negation "Download only the metadata"

### ISSUE THREAD

**Issue by sneumann** [workflow4metabolomics/mtbls-dwnld#32]
Hi, 
currently, the tools uses a non-straightforward logic about metadata/full data,
where the user has to select `No` to get more information. Several suggestions:

- Reword to "Omit raw data" (which is wrong, as everything but `?_*.t*` is omitted)
- two Radio buttons "ISA-Tab Metadata only" and "ISA-Tab Metadata incl. full stdy and raw data".

Yours, Steffen

**Comment by pkrog** [comment]
Solved by #36
