### ISSUE TITLE
Travis-CI test fails on unicode char error 

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/mtbls-dwnld#5]
[Travis-CI test 91](https://travis-ci.org/workflow4metabolomics/mtbls-dwnld/builds/245396769) fails on unicode char error:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 521635: ordinal not in range(128)
```

**Comment by pierrickrogermele** [comment]
Hi @lecorguille ,

Any idea about this error message? I looked at output of my script and output files, but did not find this unicode character.
It looks like a Python error message, right?

**Comment by lecorguille** [comment]
I don't think so!
Generally, this message is display because R like the character ` but not Planemo.
For me, the really message is:
```
Error in loadNamespace(name) : there is no package called `R.utils`
```
But to be sure, run Planemo locally if you can and look at the web report.

**Comment by pkrog** [comment]
R is no more used inside this tool.
